[project]
name = "42-multilayer-perceptron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.2",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
    "typer>=0.17.4",
]
